---
apiVersion: v1
kind: Secret
metadata:
  name: repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:argadepp/argocd.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEAzS84xMTjkFRY2DO6sONL9aWVgnszP8kK1lCvfQI3frSMhxPATPhV
    TexngpSLn+/F7xYWr3CqLC1400lci80cMpHFI3MdVN/PKbqnjh1DHiANgc8QlN/bC9WLM3
    1oQsn8cFtTvJ96Ek6KJdpBk+8PopHccJJnzOULNrgZb9gs5FzsPBvta4MYHQiUYo21EaJ2
    WgUkfD8VTjD73PPKwY8Gx4dBCAZaChCyIV2yerB8MTjOfIj2v6WyGU2Y66Y8qdTfMTeGBn
    SC67mAwrpNV+MBoMmCGCc9ItiAsqASRaPthkM7/i044DJ/fGYALKLGsT6XExkmDSwRKGVp
    6BxmMSlwHs08plHoUGZe9im5BJply0OGv4v1ZbV2OmjNn7F9kBlBEXMnTpQlDCa5doA3Qz
    kIy8vK2YbBmmQkgAfieJqbC8nrJ8DexpmIUfGAe9Gi/ef65i12rWVoGGI/7dfG46ljB1pG
    udxmlQpeZEGNne87M5Rl9Chwj/h/CvIEc6sA72n9AAAFiPmbTrn5m065AAAAB3NzaC1yc2
    EAAAGBAM0vOMTE45BUWNgzurDjS/WllYJ7Mz/JCtZQr30CN360jIcTwEz4VU3sZ4KUi5/v
    xe8WFq9wqiwteNNJXIvNHDKRxSNzHVTfzym6p44dQx4gDYHPEJTf2wvVizN9aELJ/HBbU7
    yfehJOiiXaQZPvD6KR3HCSZ8zlCza4GW/YLORc7Dwb7WuDGB0IlGKNtRGidloFJHw/FU4w
    +9zzysGPBseHQQgGWgoQsiFdsnqwfDE4znyI9r+lshlNmOumPKnU3zE3hgZ0guu5gMK6TV
    fjAaDJghgnPSLYgLKgEkWj7YZDO/4tOOAyf3xmACyixrE+lxMZJg0sEShlaegcZjEpcB7N
    PKZR6FBmXvYpuQSaZctDhr+L9WW1djpozZ+xfZAZQRFzJ06UJQwmuXaAN0M5CMvLytmGwZ
    pkJIAH4niamwvJ6yfA3saZiFHxgHvRov3n+uYtdq1laBhiP+3XxuOpYwdaRrncZpUKXmRB
    jZ3vOzOUZfQocI/4fwryBHOrAO9p/QAAAAMBAAEAAAGAYsFiqlo1SQc/x7eGGJMdwTqULj
    wL25xwydwFyr4hZauSo4TfHmy76ghpfZDvbughtURFYOVyEldEezUpBOSQuMouPzStnmcm
    N2huMtlkr4Av4BWAXpcrv5NlL0AhyVucU5uxPuzm/R6uIS/eNkxukwlvNwNQUG7BKfIL1C
    gQ20zaKsgqSn/LQFYbzR91UeqG2ib1e5OFNqAe6SaxpN2pHqm7pBgiiAunIKYPPDvrWmmE
    AK6PTIh8ou8VNf5J3lfkw8zsek7+ImnG9ezl39NQHyYMpE3fSYfBJtQ+HJwV//9nFPngHL
    jQR+8RiBuer6LRWGeAUsaEFMvf9k4aEuMrg7htivI08C6vtL+CQmKy7oC5WQvt3LHHX9Zs
    jaMTuL+60tcrPbWCwZNouqMvr+VBu7hazMhnB81BJ3U4Fw7a9OJ98qN/11XOewMqAVLlm7
    /mw6QI7Af4suBiBhhfcI/uSJqj3S9JYPzqNb6bneCwzX/M3BydSP09NDHAfjoCY59hAAAA
    wAD+XRgeq/M8hSmXSubjTtQZ/B3X3dWtHDVzzGhvaAWocuL/x0mAkLgmfFrXFO2p/lfVEM
    Mj5XOH2U36tM8D+jTT29uHJQ+QVaVTjxUQKbgZOkECydUDeY8EDeCjB1X/isLPNfjIg6O8
    DmeOiNUinNotXy9rtwmd4IIVnBk6WP61Ei8QqyoA9A+dSbznFAXrHHSvtdZruZUMg5BHPM
    dloMYMLcZiafFx0DGblYgMCNrGeN3VdqQ4np4M1HDd+Yx5CgAAAMEA8R+Rqf3HX76/3dUe
    UiPkbtll73Zslytta5RW2B7/egkgNXNnni8qHgwMSSNQQzpLBwQ93uY1D0oYnohnv94nvH
    h7asrW/eTkckSvSWorVytznPHqQH5Gd5gkAq6KRQ7tFymLuaLgxi1LsXCsOcL2oMqracei
    riNIx3mp4nV+X5D7MAQzp+yxGGk0e1bQG262Hu/v+cLbdyuNDTMujcxaAw8qr6IKOaUFPH
    Yn1NDAWB+K4Unhv44lInUHMPjaJPmVAAAAwQDZ2APikTP93NO93fQ7qsao17kw06bC/FJT
    Q+L2KkdD5hmjbwEYpZhA+A4Ld65e4GR3VahpblfSkEkxw/jZzPSWmRSarCJKG95L91sFXj
    wdmPbzUwe1EJY2EAUvQUklA393WHehHDZYgnzbWxVU0V6rL7AJVqNdWrMej7OpdhWSzLzL
    vsIph2t2lUg9gQqFpeCsHEl3dumMyxtj6AitIXhD6A8pU6+ZgSjs5hy6/J1logrN1vlxsM
    FPNBhDJ4j0pMkAAAASYXJnYWRlcHBAZ21haWwuY29tAQ==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
